baseURL = 'https://tuesdaybornwhale.github.io/'
languageCode = 'en-us'
title = 'TuesdayBornWhale'
theme = 'gohugo-theme-ananke'

[params]
  background_color_class = "bg-dark-blue"
  recent_posts_number = 4
  email = 'jsmith@example.org'
  name = 'John Smith'
  description = '''Blog dedicated to mostly Math, meta-math and AI safety.
  '''
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  


[menu]
    [[menu.main]]
    identifier = 'home'
    name = "Home"
    url = '/'
    weight = 1

    [[menu.main]]
    identifier = 'blog'
    name = "Blog"
    url = '/posts/'
    weight = 2

    [[menu.main]]
    identifier = 'about'
    name = "About me"
    url = '/about/'
    weight = 3
